<a href="https://colab.research.google.com/github/femartinsamorim/programacao-pratica_e_treinamento/blob/main/machine_learning_treinamento_02_tratamento_string_copia.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
# Separando os valores entre variáveis independentes "X" e dependentes "y" 
df = pd.read_csv('/content/notas.csv',delimiter=',')
modelo = df.iloc[:,:]
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values
print(modelo)
print('\n')
print(X)
print('\n')
print(y)

      Nome  Nota 1  Nota2  Nota3  TOEFL  Aprovado
0   Felipe      30     20     38     98         1
1   Amanda      25     23     40     96         1
2  Marcelo      15     10     30     83         0
3  Matheus      30     30     39     99         1
4  Larissa      29      0     30     95         0


[['Felipe' 30 20 38 98]
 ['Amanda' 25 23 40 96]
 ['Marcelo' 15 10 30 83]
 ['Matheus' 30 30 39 99]
 ['Larissa' 29 0 30 95]]


[1 1 0 1 0]


In [3]:
# Alterando os nomes para "rotúlos" de forma random como um ID
from sklearn.preprocessing import LabelEncoder
label_X = LabelEncoder()
X[:,0] = label_X.fit_transform(X[:,0]) 
print(X)

[[1 30 20 38 98]
 [0 25 23 40 96]
 [3 15 10 30 83]
 [4 30 30 39 99]
 [2 29 0 30 95]]


In [4]:
# Utilizando o "One-Hot Encode" para transformar os números em binários.

D = pd.get_dummies(X[:,0]) # transformação da coluna em binários
X = X[:,1:] #Removendo a coluna "0"
X = np.insert(X, 0, D.values, axis=1)
print(X)

[[0 1 0 0 0 30 20 38 98]
 [1 0 0 0 0 25 23 40 96]
 [0 0 0 0 1 15 10 30 83]
 [0 0 1 0 0 30 30 39 99]
 [0 0 0 1 0 29 0 30 95]]


<ipython-input-4-6ccf57d4adb9>:3: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  D = pd.get_dummies(X[:,0]) # transformação da coluna em binários


In [5]:
# Treino x Teste
from sklearn.model_selection import train_test_split
XTrain, Xtest, yTrain, yTest = train_test_split(X,y, test_size = 0.2) #20% em Teste
print(XTrain)

[[0 0 0 0 1 15 10 30 83]
 [0 0 0 1 0 29 0 30 95]
 [1 0 0 0 0 25 23 40 96]
 [0 0 1 0 0 30 30 39 99]]
